#set(WITH_LEDA ON CACHE BOOL "")
#set(CMAKE_EXE_LINKER_FLAGS "-L/opt/homebrew/Cellar/libx11/1.7.0/lib/ -lX11 -lpthread" CACHE STRING "")
#set(LEDA_INCLUDE_DIR "/Users/magritte/3rdPartyLibs/leda/incl/" CACHE PATH "")
#set(LEDA_LIBRARY_RELEASE "/Users/magritte/3rdPartyLibs/leda/build/libleda_numbers.dylib" CACHE PATH "")
#set(LEDA_LINKER_FLAGS "-L/opt/homebrew/Cellar/libx11/1.7.0/lib/ -lX11 -lpthread" CACHE STRING "")
#set(CGAL_DISABLE_GMP ON CACHE BOOL "")
